steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/gcp-training-346413/spring-boot-testing", "--build-arg=JAR_FILE=target/spring-boot-testing-1.0.0.jar", "."]
images: ["gcr.io/gcp-training-346413/spring-boot-testing"]