steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/gcp-training-346413/spring-boot-testing2", "--build-arg=JAR_FILE=target/spring-boot-testing-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/gcp-training-346413/spring-boot-testing2"]